// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package client

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/kaiachain/kaia/blockchain/types"
	"github.com/kaiachain/kaia/common"
	"github.com/kaiachain/kaia/common/hexutil"
)

var _ = (*headerMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (e EthHeader) MarshalJSON() ([]byte, error) {
	type EthHeader struct {
		ParentHash       common.Hash     `json:"parentHash"       gencodec:"required"`
		UncleHash        common.Hash     `json:"sha3Uncles"       gencodec:"required"`
		Coinbase         common.Address  `json:"miner"`
		Root             common.Hash     `json:"stateRoot"        gencodec:"required"`
		TxHash           common.Hash     `json:"transactionsRoot" gencodec:"required"`
		ReceiptHash      common.Hash     `json:"receiptsRoot"     gencodec:"required"`
		Bloom            types.Bloom     `json:"logsBloom"        gencodec:"required"`
		Difficulty       *hexutil.Big    `json:"difficulty"       gencodec:"required"`
		Number           *hexutil.Big    `json:"number"           gencodec:"required"`
		GasLimit         hexutil.Uint64  `json:"gasLimit"         gencodec:"required"`
		GasUsed          hexutil.Uint64  `json:"gasUsed"          gencodec:"required"`
		Time             hexutil.Uint64  `json:"timestamp"        gencodec:"required"`
		Extra            hexutil.Bytes   `json:"extraData"        gencodec:"required"`
		MixDigest        common.Hash     `json:"mixHash"`
		Nonce            BlockNonce      `json:"nonce"`
		BaseFee          *hexutil.Big    `json:"baseFeePerGas" rlp:"optional"`
		WithdrawalsHash  *common.Hash    `json:"withdrawalsRoot" rlp:"optional"`
		BlobGasUsed      *hexutil.Uint64 `json:"blobGasUsed" rlp:"optional"`
		ExcessBlobGas    *hexutil.Uint64 `json:"excessBlobGas" rlp:"optional"`
		ParentBeaconRoot *common.Hash    `json:"parentBeaconBlockRoot" rlp:"optional"`
		RequestsHash     *common.Hash    `json:"requestsHash" rlp:"optional"`
		Hash             common.Hash     `json:"hash"`
	}
	var enc EthHeader
	enc.ParentHash = e.ParentHash
	enc.UncleHash = e.UncleHash
	enc.Coinbase = e.Coinbase
	enc.Root = e.Root
	enc.TxHash = e.TxHash
	enc.ReceiptHash = e.ReceiptHash
	enc.Bloom = e.Bloom
	enc.Difficulty = (*hexutil.Big)(e.Difficulty)
	enc.Number = (*hexutil.Big)(e.Number)
	enc.GasLimit = hexutil.Uint64(e.GasLimit)
	enc.GasUsed = hexutil.Uint64(e.GasUsed)
	enc.Time = hexutil.Uint64(e.Time)
	enc.Extra = e.Extra
	enc.MixDigest = e.MixDigest
	enc.Nonce = e.Nonce
	enc.BaseFee = (*hexutil.Big)(e.BaseFee)
	enc.WithdrawalsHash = e.WithdrawalsHash
	enc.BlobGasUsed = (*hexutil.Uint64)(e.BlobGasUsed)
	enc.ExcessBlobGas = (*hexutil.Uint64)(e.ExcessBlobGas)
	enc.ParentBeaconRoot = e.ParentBeaconRoot
	enc.RequestsHash = e.RequestsHash
	enc.Hash = e.Hash()
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (e *EthHeader) UnmarshalJSON(input []byte) error {
	type EthHeader struct {
		ParentHash       *common.Hash    `json:"parentHash"       gencodec:"required"`
		UncleHash        *common.Hash    `json:"sha3Uncles"       gencodec:"required"`
		Coinbase         *common.Address `json:"miner"`
		Root             *common.Hash    `json:"stateRoot"        gencodec:"required"`
		TxHash           *common.Hash    `json:"transactionsRoot" gencodec:"required"`
		ReceiptHash      *common.Hash    `json:"receiptsRoot"     gencodec:"required"`
		Bloom            *types.Bloom    `json:"logsBloom"        gencodec:"required"`
		Difficulty       *hexutil.Big    `json:"difficulty"       gencodec:"required"`
		Number           *hexutil.Big    `json:"number"           gencodec:"required"`
		GasLimit         *hexutil.Uint64 `json:"gasLimit"         gencodec:"required"`
		GasUsed          *hexutil.Uint64 `json:"gasUsed"          gencodec:"required"`
		Time             *hexutil.Uint64 `json:"timestamp"        gencodec:"required"`
		Extra            *hexutil.Bytes  `json:"extraData"        gencodec:"required"`
		MixDigest        *common.Hash    `json:"mixHash"`
		Nonce            *BlockNonce     `json:"nonce"`
		BaseFee          *hexutil.Big    `json:"baseFeePerGas" rlp:"optional"`
		WithdrawalsHash  *common.Hash    `json:"withdrawalsRoot" rlp:"optional"`
		BlobGasUsed      *hexutil.Uint64 `json:"blobGasUsed" rlp:"optional"`
		ExcessBlobGas    *hexutil.Uint64 `json:"excessBlobGas" rlp:"optional"`
		ParentBeaconRoot *common.Hash    `json:"parentBeaconBlockRoot" rlp:"optional"`
		RequestsHash     *common.Hash    `json:"requestsHash" rlp:"optional"`
	}
	var dec EthHeader
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.ParentHash == nil {
		return errors.New("missing required field 'parentHash' for EthHeader")
	}
	e.ParentHash = *dec.ParentHash
	if dec.UncleHash == nil {
		return errors.New("missing required field 'sha3Uncles' for EthHeader")
	}
	e.UncleHash = *dec.UncleHash
	if dec.Coinbase != nil {
		e.Coinbase = *dec.Coinbase
	}
	if dec.Root == nil {
		return errors.New("missing required field 'stateRoot' for EthHeader")
	}
	e.Root = *dec.Root
	if dec.TxHash == nil {
		return errors.New("missing required field 'transactionsRoot' for EthHeader")
	}
	e.TxHash = *dec.TxHash
	if dec.ReceiptHash == nil {
		return errors.New("missing required field 'receiptsRoot' for EthHeader")
	}
	e.ReceiptHash = *dec.ReceiptHash
	if dec.Bloom == nil {
		return errors.New("missing required field 'logsBloom' for EthHeader")
	}
	e.Bloom = *dec.Bloom
	if dec.Difficulty == nil {
		return errors.New("missing required field 'difficulty' for EthHeader")
	}
	e.Difficulty = (*big.Int)(dec.Difficulty)
	if dec.Number == nil {
		return errors.New("missing required field 'number' for EthHeader")
	}
	e.Number = (*big.Int)(dec.Number)
	if dec.GasLimit == nil {
		return errors.New("missing required field 'gasLimit' for EthHeader")
	}
	e.GasLimit = uint64(*dec.GasLimit)
	if dec.GasUsed == nil {
		return errors.New("missing required field 'gasUsed' for EthHeader")
	}
	e.GasUsed = uint64(*dec.GasUsed)
	if dec.Time == nil {
		return errors.New("missing required field 'timestamp' for EthHeader")
	}
	e.Time = uint64(*dec.Time)
	if dec.Extra == nil {
		return errors.New("missing required field 'extraData' for EthHeader")
	}
	e.Extra = *dec.Extra
	if dec.MixDigest != nil {
		e.MixDigest = *dec.MixDigest
	}
	if dec.Nonce != nil {
		e.Nonce = *dec.Nonce
	}
	if dec.BaseFee != nil {
		e.BaseFee = (*big.Int)(dec.BaseFee)
	}
	if dec.WithdrawalsHash != nil {
		e.WithdrawalsHash = dec.WithdrawalsHash
	}
	if dec.BlobGasUsed != nil {
		e.BlobGasUsed = (*uint64)(dec.BlobGasUsed)
	}
	if dec.ExcessBlobGas != nil {
		e.ExcessBlobGas = (*uint64)(dec.ExcessBlobGas)
	}
	if dec.ParentBeaconRoot != nil {
		e.ParentBeaconRoot = dec.ParentBeaconRoot
	}
	if dec.RequestsHash != nil {
		e.RequestsHash = dec.RequestsHash
	}
	return nil
}
