// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kaiachain/kaia/kaiax/valset (interfaces: ValsetModule)

// Package mock_valset is a generated GoMock package.
package mock_valset

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	state "github.com/kaiachain/kaia/blockchain/state"
	types "github.com/kaiachain/kaia/blockchain/types"
	common "github.com/kaiachain/kaia/common"
	rpc "github.com/kaiachain/kaia/networks/rpc"
)

// MockValsetModule is a mock of ValsetModule interface.
type MockValsetModule struct {
	ctrl     *gomock.Controller
	recorder *MockValsetModuleMockRecorder
}

// MockValsetModuleMockRecorder is the mock recorder for MockValsetModule.
type MockValsetModuleMockRecorder struct {
	mock *MockValsetModule
}

// NewMockValsetModule creates a new mock instance.
func NewMockValsetModule(ctrl *gomock.Controller) *MockValsetModule {
	mock := &MockValsetModule{ctrl: ctrl}
	mock.recorder = &MockValsetModuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValsetModule) EXPECT() *MockValsetModuleMockRecorder {
	return m.recorder
}

// APIs mocks base method.
func (m *MockValsetModule) APIs() []rpc.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIs")
	ret0, _ := ret[0].([]rpc.API)
	return ret0
}

// APIs indicates an expected call of APIs.
func (mr *MockValsetModuleMockRecorder) APIs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIs", reflect.TypeOf((*MockValsetModule)(nil).APIs))
}

// FinalizeHeader mocks base method.
func (m *MockValsetModule) FinalizeHeader(arg0 *types.Header, arg1 *state.StateDB, arg2 []*types.Transaction, arg3 []*types.Receipt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeHeader", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinalizeHeader indicates an expected call of FinalizeHeader.
func (mr *MockValsetModuleMockRecorder) FinalizeHeader(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeHeader", reflect.TypeOf((*MockValsetModule)(nil).FinalizeHeader), arg0, arg1, arg2, arg3)
}

// GetCommitteeAddressList mocks base method.
func (m *MockValsetModule) GetCommitteeAddressList(arg0, arg1 uint64) ([]common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitteeAddressList", arg0, arg1)
	ret0, _ := ret[0].([]common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitteeAddressList indicates an expected call of GetCommitteeAddressList.
func (mr *MockValsetModuleMockRecorder) GetCommitteeAddressList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitteeAddressList", reflect.TypeOf((*MockValsetModule)(nil).GetCommitteeAddressList), arg0, arg1)
}

// GetCouncilAddressList mocks base method.
func (m *MockValsetModule) GetCouncilAddressList(arg0 uint64) ([]common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCouncilAddressList", arg0)
	ret0, _ := ret[0].([]common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCouncilAddressList indicates an expected call of GetCouncilAddressList.
func (mr *MockValsetModuleMockRecorder) GetCouncilAddressList(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCouncilAddressList", reflect.TypeOf((*MockValsetModule)(nil).GetCouncilAddressList), arg0)
}

// GetProposer mocks base method.
func (m *MockValsetModule) GetProposer(arg0, arg1 uint64) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProposer", arg0, arg1)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProposer indicates an expected call of GetProposer.
func (mr *MockValsetModuleMockRecorder) GetProposer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProposer", reflect.TypeOf((*MockValsetModule)(nil).GetProposer), arg0, arg1)
}

// PrepareHeader mocks base method.
func (m *MockValsetModule) PrepareHeader(arg0 *types.Header) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PrepareHeader indicates an expected call of PrepareHeader.
func (mr *MockValsetModuleMockRecorder) PrepareHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareHeader", reflect.TypeOf((*MockValsetModule)(nil).PrepareHeader), arg0)
}

// Start mocks base method.
func (m *MockValsetModule) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockValsetModuleMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockValsetModule)(nil).Start))
}

// Stop mocks base method.
func (m *MockValsetModule) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockValsetModuleMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockValsetModule)(nil).Stop))
}

// VerifyHeader mocks base method.
func (m *MockValsetModule) VerifyHeader(arg0 *types.Header) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyHeader indicates an expected call of VerifyHeader.
func (mr *MockValsetModuleMockRecorder) VerifyHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyHeader", reflect.TypeOf((*MockValsetModule)(nil).VerifyHeader), arg0)
}

// Vote mocks base method.
func (m *MockValsetModule) Vote(arg0 uint64, arg1 common.Address, arg2 string, arg3 interface{}) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vote", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Vote indicates an expected call of Vote.
func (mr *MockValsetModuleMockRecorder) Vote(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vote", reflect.TypeOf((*MockValsetModule)(nil).Vote), arg0, arg1, arg2, arg3)
}
