// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kaiachain/kaia/blockchain (interfaces: Message)

// Package mock_bc is a generated GoMock package.
package mock_bc

import (
	big "math/big"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/kaiachain/kaia/blockchain/types"
	common "github.com/kaiachain/kaia/common"
	params "github.com/kaiachain/kaia/params"
)

// MockMessage is a mock of Message interface.
type MockMessage struct {
	ctrl     *gomock.Controller
	recorder *MockMessageMockRecorder
}

// MockMessageMockRecorder is the mock recorder for MockMessage.
type MockMessageMockRecorder struct {
	mock *MockMessage
}

// NewMockMessage creates a new mock instance.
func NewMockMessage(ctrl *gomock.Controller) *MockMessage {
	mock := &MockMessage{ctrl: ctrl}
	mock.recorder = &MockMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessage) EXPECT() *MockMessageMockRecorder {
	return m.recorder
}

// AccessList mocks base method.
func (m *MockMessage) AccessList() types.AccessList {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessList")
	ret0, _ := ret[0].(types.AccessList)
	return ret0
}

// AccessList indicates an expected call of AccessList.
func (mr *MockMessageMockRecorder) AccessList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessList", reflect.TypeOf((*MockMessage)(nil).AccessList))
}

// AuthList mocks base method.
func (m *MockMessage) AuthList() []types.SetCodeAuthorization {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthList")
	ret0, _ := ret[0].([]types.SetCodeAuthorization)
	return ret0
}

// AuthList indicates an expected call of AuthList.
func (mr *MockMessageMockRecorder) AuthList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthList", reflect.TypeOf((*MockMessage)(nil).AuthList))
}

// BlobGasFeeCap mocks base method.
func (m *MockMessage) BlobGasFeeCap() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlobGasFeeCap")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// BlobGasFeeCap indicates an expected call of BlobGasFeeCap.
func (mr *MockMessageMockRecorder) BlobGasFeeCap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlobGasFeeCap", reflect.TypeOf((*MockMessage)(nil).BlobGasFeeCap))
}

// BlobHashes mocks base method.
func (m *MockMessage) BlobHashes() []common.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlobHashes")
	ret0, _ := ret[0].([]common.Hash)
	return ret0
}

// BlobHashes indicates an expected call of BlobHashes.
func (mr *MockMessageMockRecorder) BlobHashes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlobHashes", reflect.TypeOf((*MockMessage)(nil).BlobHashes))
}

// CheckNonce mocks base method.
func (m *MockMessage) CheckNonce() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckNonce")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckNonce indicates an expected call of CheckNonce.
func (mr *MockMessageMockRecorder) CheckNonce() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckNonce", reflect.TypeOf((*MockMessage)(nil).CheckNonce))
}

// Data mocks base method.
func (m *MockMessage) Data() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Data")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Data indicates an expected call of Data.
func (mr *MockMessageMockRecorder) Data() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Data", reflect.TypeOf((*MockMessage)(nil).Data))
}

// EffectiveGasPrice mocks base method.
func (m *MockMessage) EffectiveGasPrice(arg0 *types.Header, arg1 *params.ChainConfig) *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EffectiveGasPrice", arg0, arg1)
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// EffectiveGasPrice indicates an expected call of EffectiveGasPrice.
func (mr *MockMessageMockRecorder) EffectiveGasPrice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EffectiveGasPrice", reflect.TypeOf((*MockMessage)(nil).EffectiveGasPrice), arg0, arg1)
}

// EffectiveGasTip mocks base method.
func (m *MockMessage) EffectiveGasTip(arg0 *big.Int) *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EffectiveGasTip", arg0)
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// EffectiveGasTip indicates an expected call of EffectiveGasTip.
func (mr *MockMessageMockRecorder) EffectiveGasTip(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EffectiveGasTip", reflect.TypeOf((*MockMessage)(nil).EffectiveGasTip), arg0)
}

// Execute mocks base method.
func (m *MockMessage) Execute(arg0 types.VM, arg1 types.StateDB, arg2, arg3 uint64, arg4 *big.Int) ([]byte, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Execute indicates an expected call of Execute.
func (mr *MockMessageMockRecorder) Execute(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockMessage)(nil).Execute), arg0, arg1, arg2, arg3, arg4)
}

// FeeRatio mocks base method.
func (m *MockMessage) FeeRatio() (types.FeeRatio, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeeRatio")
	ret0, _ := ret[0].(types.FeeRatio)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// FeeRatio indicates an expected call of FeeRatio.
func (mr *MockMessageMockRecorder) FeeRatio() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeeRatio", reflect.TypeOf((*MockMessage)(nil).FeeRatio))
}

// Gas mocks base method.
func (m *MockMessage) Gas() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gas")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Gas indicates an expected call of Gas.
func (mr *MockMessageMockRecorder) Gas() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gas", reflect.TypeOf((*MockMessage)(nil).Gas))
}

// GasFeeCap mocks base method.
func (m *MockMessage) GasFeeCap() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GasFeeCap")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// GasFeeCap indicates an expected call of GasFeeCap.
func (mr *MockMessageMockRecorder) GasFeeCap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GasFeeCap", reflect.TypeOf((*MockMessage)(nil).GasFeeCap))
}

// GasPrice mocks base method.
func (m *MockMessage) GasPrice() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GasPrice")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// GasPrice indicates an expected call of GasPrice.
func (mr *MockMessageMockRecorder) GasPrice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GasPrice", reflect.TypeOf((*MockMessage)(nil).GasPrice))
}

// GasTipCap mocks base method.
func (m *MockMessage) GasTipCap() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GasTipCap")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// GasTipCap indicates an expected call of GasTipCap.
func (mr *MockMessageMockRecorder) GasTipCap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GasTipCap", reflect.TypeOf((*MockMessage)(nil).GasTipCap))
}

// Hash mocks base method.
func (m *MockMessage) Hash() common.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash")
	ret0, _ := ret[0].(common.Hash)
	return ret0
}

// Hash indicates an expected call of Hash.
func (mr *MockMessageMockRecorder) Hash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockMessage)(nil).Hash))
}

// IntrinsicGas mocks base method.
func (m *MockMessage) IntrinsicGas(arg0 uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntrinsicGas", arg0)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IntrinsicGas indicates an expected call of IntrinsicGas.
func (mr *MockMessageMockRecorder) IntrinsicGas(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntrinsicGas", reflect.TypeOf((*MockMessage)(nil).IntrinsicGas), arg0)
}

// Nonce mocks base method.
func (m *MockMessage) Nonce() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nonce")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Nonce indicates an expected call of Nonce.
func (mr *MockMessageMockRecorder) Nonce() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nonce", reflect.TypeOf((*MockMessage)(nil).Nonce))
}

// To mocks base method.
func (m *MockMessage) To() *common.Address {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "To")
	ret0, _ := ret[0].(*common.Address)
	return ret0
}

// To indicates an expected call of To.
func (mr *MockMessageMockRecorder) To() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "To", reflect.TypeOf((*MockMessage)(nil).To))
}

// Type mocks base method.
func (m *MockMessage) Type() types.TxType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(types.TxType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockMessageMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockMessage)(nil).Type))
}

// Validate mocks base method.
func (m *MockMessage) Validate(arg0 types.StateDB, arg1 types.Signer, arg2 uint64, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockMessageMockRecorder) Validate(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockMessage)(nil).Validate), arg0, arg1, arg2, arg3)
}

// ValidatedFeePayer mocks base method.
func (m *MockMessage) ValidatedFeePayer() common.Address {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatedFeePayer")
	ret0, _ := ret[0].(common.Address)
	return ret0
}

// ValidatedFeePayer indicates an expected call of ValidatedFeePayer.
func (mr *MockMessageMockRecorder) ValidatedFeePayer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatedFeePayer", reflect.TypeOf((*MockMessage)(nil).ValidatedFeePayer))
}

// ValidatedGas mocks base method.
func (m *MockMessage) ValidatedGas() *types.ValidatedGas {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatedGas")
	ret0, _ := ret[0].(*types.ValidatedGas)
	return ret0
}

// ValidatedGas indicates an expected call of ValidatedGas.
func (mr *MockMessageMockRecorder) ValidatedGas() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatedGas", reflect.TypeOf((*MockMessage)(nil).ValidatedGas))
}

// ValidatedSender mocks base method.
func (m *MockMessage) ValidatedSender() common.Address {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatedSender")
	ret0, _ := ret[0].(common.Address)
	return ret0
}

// ValidatedSender indicates an expected call of ValidatedSender.
func (mr *MockMessageMockRecorder) ValidatedSender() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatedSender", reflect.TypeOf((*MockMessage)(nil).ValidatedSender))
}

// Value mocks base method.
func (m *MockMessage) Value() *big.Int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value")
	ret0, _ := ret[0].(*big.Int)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockMessageMockRecorder) Value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockMessage)(nil).Value))
}
