// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package tests

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/kaiachain/kaia/common"
	"github.com/kaiachain/kaia/common/math"
)

var _ = (*stEnvMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (s stEnv) MarshalJSON() ([]byte, error) {
	type stEnv struct {
		Coinbase   common.UnprefixedAddress `gencodec:"required" json:"currentCoinbase"`
		BlockScore *math.HexOrDecimal256    `gencodec:"required" json:"currentDifficulty"`
		GasLimit   math.HexOrDecimal64      `gencodec:"required" json:"currentGasLimit"`
		Number     math.HexOrDecimal64      `gencodec:"required" json:"currentNumber"`
		Timestamp  math.HexOrDecimal64      `gencodec:"required" json:"currentTimestamp"`
		BaseFee    *math.HexOrDecimal256    `gencodec:"optional" json:"currentBaseFee"`
	}
	var enc stEnv
	enc.Coinbase = common.UnprefixedAddress(s.Coinbase)
	enc.BlockScore = (*math.HexOrDecimal256)(s.BlockScore)
	enc.GasLimit = math.HexOrDecimal64(s.GasLimit)
	enc.Number = math.HexOrDecimal64(s.Number)
	enc.Timestamp = math.HexOrDecimal64(s.Timestamp)
	enc.BaseFee = (*math.HexOrDecimal256)(s.BaseFee)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (s *stEnv) UnmarshalJSON(input []byte) error {
	type stEnv struct {
		Coinbase   *common.UnprefixedAddress `gencodec:"required" json:"currentCoinbase"`
		BlockScore *math.HexOrDecimal256     `gencodec:"required" json:"currentDifficulty"`
		GasLimit   *math.HexOrDecimal64      `gencodec:"required" json:"currentGasLimit"`
		Number     *math.HexOrDecimal64      `gencodec:"required" json:"currentNumber"`
		Timestamp  *math.HexOrDecimal64      `gencodec:"required" json:"currentTimestamp"`
		BaseFee    *math.HexOrDecimal256     `gencodec:"optional" json:"currentBaseFee"`
	}
	var dec stEnv
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Coinbase == nil {
		return errors.New("missing required field 'currentCoinbase' for stEnv")
	}
	s.Coinbase = common.Address(*dec.Coinbase)
	if dec.BlockScore == nil {
		return errors.New("missing required field 'currentDifficulty' for stEnv")
	}
	s.BlockScore = (*big.Int)(dec.BlockScore)
	if dec.GasLimit == nil {
		return errors.New("missing required field 'currentGasLimit' for stEnv")
	}
	s.GasLimit = uint64(*dec.GasLimit)
	if dec.Number == nil {
		return errors.New("missing required field 'currentNumber' for stEnv")
	}
	s.Number = uint64(*dec.Number)
	if dec.Timestamp == nil {
		return errors.New("missing required field 'currentTimestamp' for stEnv")
	}
	s.Timestamp = uint64(*dec.Timestamp)
	if dec.BaseFee != nil {
		s.BaseFee = (*big.Int)(dec.BaseFee)
	}
	return nil
}
