// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package tests

import (
	"encoding/json"

	"github.com/kaiachain/kaia/common/math"
)

var _ = (*btBlobConfigMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (b btBlobConfig) MarshalJSON() ([]byte, error) {
	type btBlobConfig struct {
		Target         math.HexOrDecimal64 `json:"target"`
		Max            math.HexOrDecimal64 `json:"max"`
		UpdateFraction math.HexOrDecimal64 `json:"baseFeeUpdateFraction"`
	}
	var enc btBlobConfig
	enc.Target = math.HexOrDecimal64(b.Target)
	enc.Max = math.HexOrDecimal64(b.Max)
	enc.UpdateFraction = math.HexOrDecimal64(b.UpdateFraction)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (b *btBlobConfig) UnmarshalJSON(input []byte) error {
	type btBlobConfig struct {
		Target         *math.HexOrDecimal64 `json:"target"`
		Max            *math.HexOrDecimal64 `json:"max"`
		UpdateFraction *math.HexOrDecimal64 `json:"baseFeeUpdateFraction"`
	}
	var dec btBlobConfig
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Target != nil {
		b.Target = int(*dec.Target)
	}
	if dec.Max != nil {
		b.Max = int(*dec.Max)
	}
	if dec.UpdateFraction != nil {
		b.UpdateFraction = uint64(*dec.UpdateFraction)
	}
	return nil
}
