// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kaiachain/kaia/consensus (interfaces: Engine)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	state "github.com/kaiachain/kaia/blockchain/state"
	types "github.com/kaiachain/kaia/blockchain/types"
	consensus "github.com/kaiachain/kaia/consensus"
	event "github.com/kaiachain/kaia/event"
	gov "github.com/kaiachain/kaia/kaiax/gov"
	valset "github.com/kaiachain/kaia/kaiax/valset"
	rpc "github.com/kaiachain/kaia/networks/rpc"
)

// MockEngine is a mock of Engine interface.
type MockEngine struct {
	ctrl     *gomock.Controller
	recorder *MockEngineMockRecorder
}

// MockEngineMockRecorder is the mock recorder for MockEngine.
type MockEngineMockRecorder struct {
	mock *MockEngine
}

// NewMockEngine creates a new mock instance.
func NewMockEngine(ctrl *gomock.Controller) *MockEngine {
	mock := &MockEngine{ctrl: ctrl}
	mock.recorder = &MockEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngine) EXPECT() *MockEngineMockRecorder {
	return m.recorder
}

// APIs mocks base method.
func (m *MockEngine) APIs(arg0 consensus.ChainReader) []rpc.API {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIs", arg0)
	ret0, _ := ret[0].([]rpc.API)
	return ret0
}

// APIs indicates an expected call of APIs.
func (mr *MockEngineMockRecorder) APIs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIs", reflect.TypeOf((*MockEngine)(nil).APIs), arg0)
}

// PurgeCache mocks base method.
func (m *MockEngine) PurgeCache() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PurgeCache")
}

// PurgeCache indicates an expected call of PurgeCache.
func (mr *MockEngineMockRecorder) PurgeCache() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeCache", reflect.TypeOf((*MockEngine)(nil).PurgeCache))
}

// RegisterKaiaxModules mocks base method.
func (m *MockEngine) RegisterKaiaxModules(arg0 gov.GovModule, arg1 valset.ValsetModule) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterKaiaxModules", arg0, arg1)
}

// RegisterKaiaxModules indicates an expected call of RegisterKaiaxModules.
func (mr *MockEngineMockRecorder) RegisterKaiaxModules(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterKaiaxModules", reflect.TypeOf((*MockEngine)(nil).RegisterKaiaxModules), arg0, arg1)
}

// Start mocks base method.
func (m *MockEngine) Start(arg0 consensus.ChainReader, arg1 consensus.Executor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockEngineMockRecorder) Start(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockEngine)(nil).Start), arg0, arg1)
}

// Stop mocks base method.
func (m *MockEngine) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockEngineMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockEngine)(nil).Stop))
}

// SubmitTransactions mocks base method.
func (m *MockEngine) SubmitTransactions(arg0 *types.TransactionsByPriceAndNonce, arg1 *state.StateDB, arg2 *types.Header, arg3 *event.TypeMux, arg4 func(*consensus.ExecutionResult)) <-chan *consensus.ExecutionResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitTransactions", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(<-chan *consensus.ExecutionResult)
	return ret0
}

// SubmitTransactions indicates an expected call of SubmitTransactions.
func (mr *MockEngineMockRecorder) SubmitTransactions(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitTransactions", reflect.TypeOf((*MockEngine)(nil).SubmitTransactions), arg0, arg1, arg2, arg3, arg4)
}

// SubscribeNewSequence mocks base method.
func (m *MockEngine) SubscribeNewSequence() *event.TypeMuxSubscription {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeNewSequence")
	ret0, _ := ret[0].(*event.TypeMuxSubscription)
	return ret0
}

// SubscribeNewSequence indicates an expected call of SubscribeNewSequence.
func (mr *MockEngineMockRecorder) SubscribeNewSequence() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeNewSequence", reflect.TypeOf((*MockEngine)(nil).SubscribeNewSequence))
}
