// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kaiachain/kaia/kaiax/vrank (interfaces: VRankModule)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	state "github.com/kaiachain/kaia/blockchain/state"
	types "github.com/kaiachain/kaia/blockchain/types"
	common "github.com/kaiachain/kaia/common"
	istanbul "github.com/kaiachain/kaia/consensus/istanbul"
	event "github.com/kaiachain/kaia/event"
	vrank "github.com/kaiachain/kaia/kaiax/vrank"
)

// MockVRankModule is a mock of VRankModule interface.
type MockVRankModule struct {
	ctrl     *gomock.Controller
	recorder *MockVRankModuleMockRecorder
}

// MockVRankModuleMockRecorder is the mock recorder for MockVRankModule.
type MockVRankModuleMockRecorder struct {
	mock *MockVRankModule
}

// NewMockVRankModule creates a new mock instance.
func NewMockVRankModule(ctrl *gomock.Controller) *MockVRankModule {
	mock := &MockVRankModule{ctrl: ctrl}
	mock.recorder = &MockVRankModuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVRankModule) EXPECT() *MockVRankModuleMockRecorder {
	return m.recorder
}

// FinalizeHeader mocks base method.
func (m *MockVRankModule) FinalizeHeader(arg0 *types.Header, arg1 *state.StateDB, arg2 []*types.Transaction, arg3 []*types.Receipt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeHeader", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinalizeHeader indicates an expected call of FinalizeHeader.
func (mr *MockVRankModuleMockRecorder) FinalizeHeader(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeHeader", reflect.TypeOf((*MockVRankModule)(nil).FinalizeHeader), arg0, arg1, arg2, arg3)
}

// GetCFS mocks base method.
func (m *MockVRankModule) GetCFS(arg0 uint64) (map[common.Address]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCFS", arg0)
	ret0, _ := ret[0].(map[common.Address]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCFS indicates an expected call of GetCFS.
func (mr *MockVRankModuleMockRecorder) GetCFS(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCFS", reflect.TypeOf((*MockVRankModule)(nil).GetCFS), arg0)
}

// GetCFSWithEpochVACount mocks base method.
func (m *MockVRankModule) GetCFSWithEpochVACount(arg0, arg1 uint64) (map[common.Address]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCFSWithEpochVACount", arg0, arg1)
	ret0, _ := ret[0].(map[common.Address]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCFSWithEpochVACount indicates an expected call of GetCFSWithEpochVACount.
func (mr *MockVRankModuleMockRecorder) GetCFSWithEpochVACount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCFSWithEpochVACount", reflect.TypeOf((*MockVRankModule)(nil).GetCFSWithEpochVACount), arg0, arg1)
}

// GetPFS mocks base method.
func (m *MockVRankModule) GetPFS(arg0 uint64) (map[common.Address]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPFS", arg0)
	ret0, _ := ret[0].(map[common.Address]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPFS indicates an expected call of GetPFS.
func (mr *MockVRankModuleMockRecorder) GetPFS(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPFS", reflect.TypeOf((*MockVRankModule)(nil).GetPFS), arg0)
}

// GetPfReport mocks base method.
func (m *MockVRankModule) GetPfReport(arg0 uint64) ([]common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPfReport", arg0)
	ret0, _ := ret[0].([]common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPfReport indicates an expected call of GetPfReport.
func (mr *MockVRankModuleMockRecorder) GetPfReport(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPfReport", reflect.TypeOf((*MockVRankModule)(nil).GetPfReport), arg0)
}

// HandleIstanbulPreprepare mocks base method.
func (m *MockVRankModule) HandleIstanbulPreprepare(arg0 *types.Block, arg1 *istanbul.View) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleIstanbulPreprepare", arg0, arg1)
}

// HandleIstanbulPreprepare indicates an expected call of HandleIstanbulPreprepare.
func (mr *MockVRankModuleMockRecorder) HandleIstanbulPreprepare(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleIstanbulPreprepare", reflect.TypeOf((*MockVRankModule)(nil).HandleIstanbulPreprepare), arg0, arg1)
}

// HandleVRankCandidate mocks base method.
func (m *MockVRankModule) HandleVRankCandidate(arg0 *vrank.VRankCandidate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleVRankCandidate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleVRankCandidate indicates an expected call of HandleVRankCandidate.
func (mr *MockVRankModuleMockRecorder) HandleVRankCandidate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleVRankCandidate", reflect.TypeOf((*MockVRankModule)(nil).HandleVRankCandidate), arg0)
}

// HandleVRankPreprepare mocks base method.
func (m *MockVRankModule) HandleVRankPreprepare(arg0 *vrank.VRankPreprepare) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleVRankPreprepare", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleVRankPreprepare indicates an expected call of HandleVRankPreprepare.
func (mr *MockVRankModuleMockRecorder) HandleVRankPreprepare(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleVRankPreprepare", reflect.TypeOf((*MockVRankModule)(nil).HandleVRankPreprepare), arg0)
}

// PrepareHeader mocks base method.
func (m *MockVRankModule) PrepareHeader(arg0 *types.Header) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PrepareHeader indicates an expected call of PrepareHeader.
func (mr *MockVRankModuleMockRecorder) PrepareHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareHeader", reflect.TypeOf((*MockVRankModule)(nil).PrepareHeader), arg0)
}

// Start mocks base method.
func (m *MockVRankModule) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockVRankModuleMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockVRankModule)(nil).Start))
}

// Stop mocks base method.
func (m *MockVRankModule) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockVRankModuleMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockVRankModule)(nil).Stop))
}

// SubscribeVRank mocks base method.
func (m *MockVRankModule) SubscribeVRank(arg0 chan<- *vrank.VRankBroadcastEvent) event.Subscription {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeVRank", arg0)
	ret0, _ := ret[0].(event.Subscription)
	return ret0
}

// SubscribeVRank indicates an expected call of SubscribeVRank.
func (mr *MockVRankModuleMockRecorder) SubscribeVRank(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeVRank", reflect.TypeOf((*MockVRankModule)(nil).SubscribeVRank), arg0)
}

// TallyCfReport mocks base method.
func (m *MockVRankModule) TallyCfReport(arg0, arg1 uint64) ([]common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TallyCfReport", arg0, arg1)
	ret0, _ := ret[0].([]common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TallyCfReport indicates an expected call of TallyCfReport.
func (mr *MockVRankModuleMockRecorder) TallyCfReport(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TallyCfReport", reflect.TypeOf((*MockVRankModule)(nil).TallyCfReport), arg0, arg1)
}

// VerifyHeader mocks base method.
func (m *MockVRankModule) VerifyHeader(arg0 *types.Header) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyHeader indicates an expected call of VerifyHeader.
func (mr *MockVRankModuleMockRecorder) VerifyHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyHeader", reflect.TypeOf((*MockVRankModule)(nil).VerifyHeader), arg0)
}
