// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kaiachain/kaia/node/cn (interfaces: Miner)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	state "github.com/kaiachain/kaia/blockchain/state"
	types "github.com/kaiachain/kaia/blockchain/types"
	kaiax "github.com/kaiachain/kaia/kaiax"
	valset "github.com/kaiachain/kaia/kaiax/valset"
	vrank "github.com/kaiachain/kaia/kaiax/vrank"
)

// MockMiner is a mock of Miner interface.
type MockMiner struct {
	ctrl     *gomock.Controller
	recorder *MockMinerMockRecorder
}

// MockMinerMockRecorder is the mock recorder for MockMiner.
type MockMinerMockRecorder struct {
	mock *MockMiner
}

// NewMockMiner creates a new mock instance.
func NewMockMiner(ctrl *gomock.Controller) *MockMiner {
	mock := &MockMiner{ctrl: ctrl}
	mock.recorder = &MockMinerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiner) EXPECT() *MockMinerMockRecorder {
	return m.recorder
}

// Mining mocks base method.
func (m *MockMiner) Mining() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mining")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Mining indicates an expected call of Mining.
func (mr *MockMinerMockRecorder) Mining() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mining", reflect.TypeOf((*MockMiner)(nil).Mining))
}

// Pending mocks base method.
func (m *MockMiner) Pending() (*types.Block, types.Receipts, *state.StateDB) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pending")
	ret0, _ := ret[0].(*types.Block)
	ret1, _ := ret[1].(types.Receipts)
	ret2, _ := ret[2].(*state.StateDB)
	return ret0, ret1, ret2
}

// Pending indicates an expected call of Pending.
func (mr *MockMinerMockRecorder) Pending() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pending", reflect.TypeOf((*MockMiner)(nil).Pending))
}

// PendingBlock mocks base method.
func (m *MockMiner) PendingBlock() *types.Block {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingBlock")
	ret0, _ := ret[0].(*types.Block)
	return ret0
}

// PendingBlock indicates an expected call of PendingBlock.
func (mr *MockMinerMockRecorder) PendingBlock() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingBlock", reflect.TypeOf((*MockMiner)(nil).PendingBlock))
}

// RegisterExecutionModule mocks base method.
func (m *MockMiner) RegisterExecutionModule(arg0 ...kaiax.ExecutionModule) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "RegisterExecutionModule", varargs...)
}

// RegisterExecutionModule indicates an expected call of RegisterExecutionModule.
func (mr *MockMinerMockRecorder) RegisterExecutionModule(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterExecutionModule", reflect.TypeOf((*MockMiner)(nil).RegisterExecutionModule), arg0...)
}

// RegisterTxBundlingModule mocks base method.
func (m *MockMiner) RegisterTxBundlingModule(arg0 ...kaiax.TxBundlingModule) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "RegisterTxBundlingModule", varargs...)
}

// RegisterTxBundlingModule indicates an expected call of RegisterTxBundlingModule.
func (mr *MockMinerMockRecorder) RegisterTxBundlingModule(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterTxBundlingModule", reflect.TypeOf((*MockMiner)(nil).RegisterTxBundlingModule), arg0...)
}

// RegisterVRankModule mocks base method.
func (m *MockMiner) RegisterVRankModule(arg0 vrank.VRankModule) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterVRankModule", arg0)
}

// RegisterVRankModule indicates an expected call of RegisterVRankModule.
func (mr *MockMinerMockRecorder) RegisterVRankModule(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterVRankModule", reflect.TypeOf((*MockMiner)(nil).RegisterVRankModule), arg0)
}

// RegisterValsetModule mocks base method.
func (m *MockMiner) RegisterValsetModule(arg0 valset.ValsetModule) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterValsetModule", arg0)
}

// RegisterValsetModule indicates an expected call of RegisterValsetModule.
func (mr *MockMinerMockRecorder) RegisterValsetModule(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterValsetModule", reflect.TypeOf((*MockMiner)(nil).RegisterValsetModule), arg0)
}

// SetExtra mocks base method.
func (m *MockMiner) SetExtra(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExtra", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetExtra indicates an expected call of SetExtra.
func (mr *MockMinerMockRecorder) SetExtra(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExtra", reflect.TypeOf((*MockMiner)(nil).SetExtra), arg0)
}

// Start mocks base method.
func (m *MockMiner) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockMinerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockMiner)(nil).Start))
}

// Stop mocks base method.
func (m *MockMiner) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockMinerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockMiner)(nil).Stop))
}
