name: Main workflow

on:
  push:
    branches:
      - test/github-action

env:
  DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  FRONTEND_BUCKET: ${{ secrets.FRONTEND_BUCKET }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  test-full:
    uses: ./.github/workflows/test-pr-workflow.yml

  check-tagger:
    runs-on: ubuntu-latest
    steps:
      - id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "match=true" >> $GITHUB_OUTPUT
          fi
      - if: steps.check-tag.outputs.match == true
        run: echo "Tag is good"

  # Docker build
  docker:
    needs: [test-full, check-tagger]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_LOGIN }}
          password: ${{ env.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            kaiachain/kaia:${{ github.ref == 'refs/heads/dev' && 'dev' || github.ref_name }}
            ${{ startsWith(github.ref, 'refs/tags/v') && 'kaiachain/kaia:latest' || '' }} 


  # Packing
  rpm-linux-amd64:
    needs: [test-full, check-tagger]
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    container:
      image: kaiachain/circleci-rpmbuild:1.23.7-gcc11

    steps:
      - uses: actions/checkout@v4

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: SessionForKaiaActions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set version
        shell: bash
        run: |
          export GOPATH=/go
          if [[ $GITHUB_REF_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+.* ]]; then
            rc_num=$(echo $GITHUB_REF_NAME | cut -d '-' -f 2)
            sed 's/%d.%d.%d/%d.%d.%d~'$rc_num'/' params/version.go > params/version.go.tmp
            mv params/version.go.tmp params/version.go
          fi
          echo "KAIA_VERSION=$(go run build/rpm/main.go version)" >> $GITHUB_ENV

      - name: Build binaries
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          make all

      - name: Build RPM packages
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --system --add safe.directory $GITHUB_WORKSPACE
          for item in kcn kpn ken kgen kscn kbn kspn ksen homi; do
            ./build/package-rpm.sh $item
          done
          
          for item in kcn kpn ken; do
            ./build/package-rpm.sh -b $item
          done

      - name: Upload RPM packages to S3
        run: |
          PLATFORM_SUFFIX=$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)
          
          for item in kcn kpn ken kcn-kairos kpn-kairos ken-kairos kgen kscn kbn kspn ksen homi; do
            BINARY=$item
            KAIROS=""
            if [[ $BINARY = *-kairos ]]; then
              BINARY="${BINARY%-kairos}"
              KAIROS="-kairos"
            fi
            TARGET_RPM=$(find $BINARY-$PLATFORM_SUFFIX/rpmbuild/RPMS/$(uname -m)/ | awk -v pat="$BINARY(d)?$KAIROS-v" '$0~pat')
            aws s3 cp $TARGET_RPM s3://$FRONTEND_BUCKET/packages/rhel/9-stream/kaia/
            aws s3 cp $TARGET_RPM s3://$FRONTEND_BUCKET/packages/kaia/$KAIA_VERSION/
          done

  tar-linux-amd64:
    needs: [test-full, check-tagger]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    container:
      image: kaiachain/build_base:go1.23.7-solc0.8.13-ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: SessionForKaiaActions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set version
        shell: bash
        run: |
          if [[ $GITHUB_REF_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+.* ]]; then
            rc_num=$(echo $GITHUB_REF_NAME | cut -d '-' -f 2)
            sed 's/%d.%d.%d/%d.%d.%d~'$rc_num'/' params/version.go > params/version.go.tmp
            mv params/version.go.tmp params/version.go
          fi
          echo "KAIA_VERSION=$(go run build/rpm/main.go version)" >> $GITHUB_ENV

      - name: Build binaries
        run: |
          git config --global --add safe.directory /__w/kaia/kaia
          make all

      - name: Build tar packages
        run: |
          for item in kcn kpn ken kgen kscn kbn kspn ksen homi; do
            ./build/package-tar.sh linux-amd64 $item
          done
          
          for item in kcn kpn ken; do
            ./build/package-tar.sh -b linux-amd64 $item
          done

      - name: Upload tar packages to S3
        run: |
          for item in kcn kpn ken kcn-kairos kpn-kairos ken-kairos kgen kscn kbn kspn ksen homi; do
            aws s3 cp packages/${item}-v*.tar.gz s3://$FRONTEND_BUCKET/packages/kaia/$KAIA_VERSION/
          done

  rpm-linux-arm64:
    needs: [test-full, check-tagger]
    runs-on: ['arm-runner']
    permissions:
      id-token: write
    container:
      image: kaiachain/circleci-rpmbuild:1.23.7-gcc11-arm
    steps:
      - uses: actions/checkout@v4

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: SessionForKaiaActions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set version
        shell: bash
        run: |
          export GOPATH=/go
          if [[ $GITHUB_REF_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+.* ]]; then
            rc_num=$(echo $GITHUB_REF_NAME | cut -d '-' -f 2)
            sed 's/%d.%d.%d/%d.%d.%d~'$rc_num'/' params/version.go > params/version.go.tmp
            mv params/version.go.tmp params/version.go
          fi
          echo "KAIA_VERSION=$(go run build/rpm/main.go version)" >> $GITHUB_ENV

      - name: Build binaries
        run: |
          git config --global --add safe.directory /__w/kaia/kaia
          make all

      - name: Build RPM packages
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --system --add safe.directory $GITHUB_WORKSPACE
          for item in kcn kpn ken kgen kscn kbn kspn ksen homi; do
            ./build/package-rpm.sh $item
          done
          
          for item in kcn kpn ken; do
            ./build/package-rpm.sh -b $item
          done

      - name: Upload RPM packages to S3
        run: |
          PLATFORM_SUFFIX=$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)
          
          for item in kcn kpn ken kcn-kairos kpn-kairos ken-kairos kgen kscn kbn kspn ksen homi; do
            BINARY=$item
            KAIROS=""
            if [[ $BINARY = *-kairos ]]; then
              BINARY="${BINARY%-kairos}"
              KAIROS="-kairos"
            fi
            TARGET_RPM=$(find $BINARY-$PLATFORM_SUFFIX/rpmbuild/RPMS/$(uname -m)/ | awk -v pat="$BINARY(d)?$KAIROS-v" '$0~pat')
            aws s3 cp $TARGET_RPM s3://$FRONTEND_BUCKET/packages/rhel/9-stream/kaia/
            aws s3 cp $TARGET_RPM s3://$FRONTEND_BUCKET/packages/kaia/$KAIA_VERSION/
          done

  tar-linux-arm64:
    needs: [test-full, check-tagger]
    runs-on: ['arm-runner']
    permissions:
      id-token: write
    container:
      image: kaiachain/build_base:go1.23.7-solc0.8.13-ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: SessionForKaiaActions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set version
        shell: bash
        run: |
          if [[ $GITHUB_REF_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+.* ]]; then
            rc_num=$(echo $GITHUB_REF_NAME | cut -d '-' -f 2)
            sed 's/%d.%d.%d/%d.%d.%d~'$rc_num'/' params/version.go > params/version.go.tmp
            mv params/version.go.tmp params/version.go
          fi
          echo "KAIA_VERSION=$(go run build/rpm/main.go version)" >> $GITHUB_ENV

      - name: Build binaries
        run: |
          git config --global --add safe.directory /__w/kaia/kaia
          make all

      - name: Build tar packages
        run: |
          for item in kcn kpn ken kgen kscn kbn kspn ksen homi; do
            ./build/package-tar.sh linux-arm64 $item
          done
          
          for item in kcn kpn ken; do
            ./build/package-tar.sh -b linux-arm64 $item
          done

      - name: Upload tar packages to S3
        run: |
          for item in kcn kpn ken kcn-kairos kpn-kairos ken-kairos kgen kscn kbn kspn ksen homi; do
            aws s3 cp packages/${item}-v*.tar.gz s3://$FRONTEND_BUCKET/packages/kaia/$KAIA_VERSION/
          done

  deploy-rpm:
    needs: [rpm-linux-amd64, tar-linux-amd64, tar-linux-arm64, rpm-linux-arm64]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    container:
      image: kaiachain/circleci-rpmbuild:1.23.7-gcc11

    steps:
      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: SessionForKaiaActions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update RPM repository
        run: |
          aws s3 sync s3://$FRONTEND_BUCKET/packages/rhel/9-stream/kaia/ rhel/9-stream/kaia/
          createrepo --update rhel/9-stream/kaia
          aws s3 sync --delete rhel/9-stream/kaia/repodata/ s3://$FRONTEND_BUCKET/packages/rhel/9-stream/kaia/repodata/
      - name: Notify Slack on success
        if: success()
        run: |
          curl --data '{"text": "✅ Package deployment succeeded for ${{ github.ref_name }}. See ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' "$SLACK_WEBHOOK_URL"
      - name: Notify Slack on failure
        if: failure()
        run: |
          curl --data '{"text": "❌ Package deployment failed for ${{ github.ref_name }}. See ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' "$SLACK_WEBHOOK_URL" 

  # Release
  release:
    needs: [rpm-linux-amd64, tar-linux-amd64, tar-linux-arm64, rpm-linux-arm64, deploy-rpm]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.changelog.outputs.changelog}}
          draft: false
          prerelease: ${{ contains(github.ref, '-rc.') }}
          files: |
            packages/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 