name: Nightly Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  push:
    branches:
      - 'test/github-action'
permissions: write-all
#env:
#  DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
#  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: kaiachain/build_base:go1.23-solc0.8.13-ubuntu-22.04
    
    steps:
      - uses: ./.github/workflows/test-other-excutor.yml
        with:
          test_command: |
            git config --global --add safe.directory /__w/kaia/kaia
            set -e
            export GOPATH=/go
            git clone --depth 1 https://github.com/kaiachain/kaia-core-tests.git tests/testdata
            make cover
            mkdir -p /tmp/coverage_reports
            cp coverage_report.txt /tmp/coverage_reports/
            cp coverage_report.html /tmp/coverage_reports/
        secrets:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}