name: Testing Workflow

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

# Run the 'build' job first to update the build cache.
jobs:
  build:
    name: Build
    uses: ./.github/workflows/test-executor-template.yml
    with:
      test_command: make kcn && make all -j

  test-linter:
    needs: build
    name: Test Linter
    uses: ./.github/workflows/test-executor-template.yml
    with:
      fetch_depth: 0
      test_command: |
        BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
        go run build/ci.go lint -v --new-from-rev="origin/${BASE_BRANCH}"

  test-networks:
    needs: build
    name: Test Networks
    uses: ./.github/workflows/test-executor-template.yml
    with:
      test_command: make test-networks

  test-node:
    needs: build
    name: Test Node
    uses: ./.github/workflows/test-executor-template.yml
    with:
      test_command: make test-node

  test-tests:
    needs: build
    name: Test Tests
    uses: ./.github/workflows/test-executor-template.yml
    with:
      test_command: |
        git clone --depth 1 https://github.com/kaiachain/kaia-core-tests.git tests/testdata
        make test-tests

  test-rpc:
    needs: build
    name: Test RPC
    permissions:
      contents: write
    uses: ./.github/workflows/test-executor-template.yml
    with:
      runs_on: ubuntu-latest
      install_python: true
      test_command: |
        make kcn
        git clone https://github.com/kaiachain/kaia-rpc-tester.git
        cd kaia-rpc-tester
        cp ../build/bin/kcn script/cn/bin/
        cd script
        ./set_CNonly.sh
        cd ..
        cp config_template.json config.json
        python3 -m venv venv
        source venv/bin/activate
        pip3 install -r requirements.txt
        python3 main.py --protocol rpc

  # Service-dependent test jobs
  test-datasync:
    needs: build
    name: Test Datasync
    uses: ./.github/workflows/test-executor-template.yml
    with:
      runs_on: kaia-xlarge-runner
      with_services: true
      test_command: make test-datasync

  test-others:
    needs: build
    name: Test Others
    uses: ./.github/workflows/test-executor-template.yml
    with:
      runs_on: kaia-xlarge-runner
      with_services: true
      test_command: make test-others
